USE [master];
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'OK2SHIP_SMT')
BEGIN
    CREATE DATABASE [OK2SHIP_SMT];
END
GO

-- Tối ưu: Cho phép đọc dữ liệu khi đang ghi (tránh deadlock)
ALTER DATABASE [OK2SHIP_SMT] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [OK2SHIP_SMT] SET READ_COMMITTED_SNAPSHOT ON;
GO