version: '3.8'

services:
    # --- 1. DATABASE ---
    db:
        build: ./1.Database
        container_name: sql_server_ok2Ship2.0
        user: "0:0"
        ports:
            - "${DB_PORT}:1433" # Đã chuyển port ra .env
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
            - MSSQL_PID=Express
            - TAINT_BIT_CORRUPTION=0
            - MSSQL_USER=root # Thử ép tham số môi trường nhận diện root
        volumes:
            - mssql_data_volume:/var/opt/mssql/data
            - mssql_log_volume:/var/opt/mssql/log
        restart: always

    # --- 2. VÍ NÓNG (HOT STORAGE - SSD) ---
    minio-hot:
        build:
            context: ./2.object_storage
            dockerfile: Dockerfile
        container_name: ok2ship_storage_hot
        env_file: .env
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER_HOT}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD_HOT}
        ports:
            - "${MINIO_HOT_API_PORT}:9000"
            - "${MINIO_HOT_CONSOLE_PORT}:9001"
        volumes:
            - ${FOLDER_PATH_SSD}/data1:/data1
            - ${FOLDER_PATH_SSD}/data2:/data2
            - ${FOLDER_PATH_SSD}/data3:/data3
            - ${FOLDER_PATH_SSD}/data4:/data4
        command: server /data1 /data2 /data3 /data4 --console-address ":9001"
        restart: always

    # --- 3. VÍ LẠNH (COLD STORAGE - HDD) ---
    minio-cold:
        build:
            context: ./2.object_storage
            dockerfile: Dockerfile
        container_name: ok2ship_storage_cold
        env_file: .env
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER_COLD}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD_COLD}
        ports:
            - "${MINIO_COLD_API_PORT}:9000" 
            - "${MINIO_COLD_CONSOLE_PORT}:9001" 
        volumes:
            - ${FOLDER_PATH_HDD}/data:/data
        command: server /data --console-address ":9001"
        restart: always

    # --- 4. TỰ ĐỘNG HÓA TOÀN BỘ (SETUP & POLICY) ---
    minio-setup:
        image: minio/mc:latest
        container_name: minio_automation_full
        depends_on:
            - minio-hot
            - minio-cold
        env_file: .env
        volumes:
        # Chú ý đường dẫn: trỏ vào folder 2.Object_storage
            - ./2.Object_storage/setup-minio.sh:/setup-minio.sh
        # Cấp quyền và thực thi script
        entrypoint: ["/bin/sh", "-c", "chmod +x /setup-minio.sh && /setup-minio.sh"]

    # --- 5. ỨNG DỤNG BACKEND (API) ---
    api-upload-image:
        container_name: api-upload-image
        build:
            context: ./3.Upload_API/Upload_API_NET           
            dockerfile: API/Dockerfile  
        ports:
            - "${API_UPLOAD_PORT}:8080" # Đã chuyển port ra .env
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        restart: unless-stopped

    # --- 6. Redis service ---
    redis_cache:
        image: redis:7-alpine
        container_name: ok2ship_redis
        restart: always
        ports:
            - "${REDIS_PORT}:6379" # Đã chuyển port ra .env
        command: redis-server --save 60 1 --loglevel warning
        volumes:
            - redis_data:/data

volumes:
  mssql_data_volume:
  mssql_log_volume:
  redis_data: